version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: rafao/simple-reverse-proxy 
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: rafao/udagram-backend-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: rafao/udagram-backend-feed
  frontend:
    build:
      context: ../../udacity-c3-frontend  
    image: rafao/udagram-frontend
